@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/golang.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/font-awesome-6/book.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/main/icons/devicons/react.puml

AddRelTag("stream", $lineStyle = DashedLine())
Container(browser, "Browser", "HTML/CSS/Javascript")
System_Boundary(multitenancy_system, "Multi-Tenancy System") {
    Container(multitenancy_api, "Server-Side Application", "Golang + Templates", $sprite="golang", "Serves HTML Templates")
    Container(user_controller, "User Controller", "Component", "Allows users to watch product's videos")
    Rel(multitenancy_api, user_controller, "Makes call to", "In-Memory Call")
}
ContainerDb(multitenancy_db_product1, "Product1 Database", "SQL")
ContainerDb(multitenancy_db_product2, "Product2 Database", "SQL")
Rel(browser, multitenancy_api, "Watch product's video using", "HTTPS")
Rel(browser, multitenancy_api, "Download product's video using", "HTTPS")
Rel(user_controller, multitenancy_db_product1, "Reads/Writes using", "HTTPS")
Rel(user_controller, multitenancy_db_product2, "Reads/Writes using", "HTTPS")
@enduml